services:
  cosy-voice:
    build:
      context: .
      dockerfile: Dockerfile
    image: cosy-voice:latest
    command: ['python3', 'webui.py', '--port', '50000', '--model_dir', 'pretrained_models/CosyVoice-300M' ]
    volumes:
      - ./pretrained_models/:/workspace/CosyVoice/pretrained_models
    ports:
      - 50000:50000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [ gpu, video ]